import { API_URL } from '../../config/api';
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { 
  Search, Calendar, Download, Eye, MoreVertical, 
  Heart, Users, CheckCircle2, Clock, XCircle, ChevronDown, ChevronLeft, ChevronRight,
  Crown, MessageCircle
} from "lucide-react";
import { getAccessToken } from "@/lib/auth-context";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { 
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow 
} from "@/components/ui/table";
import { format } from "date-fns";
import { motion, AnimatePresence } from "framer-motion";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { LineChart, Line, ResponsiveContainer } from "recharts";

const sparklineData = [
  { value: 10 }, { value: 20 }, { value: 15 }, { value: 25 }, { value: 30 }, { value: 45 }, { value: 40 }
];

const fetchStats = async () => {
  const res = await fetch(`${API_URL}/api/admin/matches/stats`, {
    headers: { Authorization: `Bearer ${getAccessToken()}` },
  });
  if (!res.ok) throw new Error("Failed to fetch stats");
  return res.json();
};

const fetchMatches = async (page: number, search: string, status: string) => {
  const params = new URLSearchParams({
    page: page.toString(),
    limit: "10",
    ...(search && { search }),
    ...(status && status !== "All" && { status })
  });
  const res = await fetch(`${API_URL}/api/admin/matches?${params.toString()}`, {
    headers: { Authorization: `Bearer ${getAccessToken()}` },
  });
  if (!res.ok) throw new Error("Failed to fetch matches");
  return res.json();
};

export default function MatchesManagement() {
  const [page, setPage] = useState(1);
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("All");
  const [typeFilter, setTypeFilter] = useState("All");
  const [compFilter, setCompFilter] = useState("All");
  
  const [selectedMatch, setSelectedMatch] = useState<any | null>(null);

  const { data: statsData } = useQuery({
    queryKey: ["adminMatchesStats"],
    queryFn: fetchStats,
    refetchInterval: 30000,
  });

  const { data: matchesData, isLoading } = useQuery({
    queryKey: ["adminMatches", page, search, statusFilter],
    queryFn: () => fetchMatches(page, search, statusFilter),
    refetchInterval: 30000,
  });

  const StatCard = ({ title, value, trend, trendUp, icon: Icon, color, lineData }: any) => (
    <div className="bg-card border border-border shadow-md rounded-2xl p-5 rounded-2xl border border-white/5 relative overflow-hidden flex flex-col justify-between">
      <div className="flex items-center gap-3 mb-2">
        <div className={`w-8 h-8 rounded-full flex items-center justify-center ${color.bg}`}>
          <Icon className={`w-4 h-4 ${color.text}`} />
        </div>
        <h3 className="text-sm font-medium text-[#707070]">{title}</h3>
      </div>
      <div>
        <div className="text-2xl font-bold mb-1">{value}</div>
        <div className={`text-xs ${trendUp ? "text-green-400" : "text-red-400"}`}>{trend}</div>
      </div>
      <div className="absolute bottom-0 left-0 right-0 h-10 opacity-30">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={lineData || sparklineData}>
            <Line type="monotone" dataKey="value" stroke={color.hex} strokeWidth={2} dot={false} />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );

  return (
    <div className="p-6 md:p-8 flex-1 overflow-y-auto">
      <div className="max-w-7xl mx-auto space-y-6">
        
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div>
            <h1 className="text-2xl font-bold">Matches Management</h1>
            <p className="text-sm text-[#707070]">View and manage all matches generated by our compatibility engine.</p>
          </div>
          <div className="flex items-center gap-3">
            <Button variant="outline" className="border-white/10 bg-card/5">
              <Calendar className="w-4 h-4 mr-2" /> May 7 - Jun 7, 2024 <ChevronDown className="w-4 h-4 ml-2" />
            </Button>
            <Button variant="outline" className="border-white/10 bg-card/5 text-[#F6A8B7] hover:text-[#F6A8B7]">
              <Download className="w-4 h-4 mr-2" /> Export Report
            </Button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          <StatCard title="Total Matches" value={statsData?.totalMatches?.value || 0} trend={statsData?.totalMatches?.trend || "+0%"} trendUp={true} icon={Heart} color={{ bg: "bg-[#F6A8B7]/20", text: "text-[#F6A8B7]", hex: "#A855F7" }} />
          <StatCard title="Accepted Matches" value={statsData?.acceptedMatches?.value || 0} trend={statsData?.acceptedMatches?.trend || "+0%"} trendUp={true} icon={CheckCircle2} color={{ bg: "bg-green-500/20", text: "text-green-400", hex: "#22C55E" }} />
          <StatCard title="Pending Matches" value={statsData?.pendingMatches?.value || 0} trend={statsData?.pendingMatches?.trend || "+0%"} trendUp={true} icon={Clock} color={{ bg: "bg-[#F6A8B7]/20", text: "text-[#F6A8B7]", hex: "#F97316" }} />
          <StatCard title="Rejected Matches" value={statsData?.rejectedMatches?.value || 0} trend={statsData?.rejectedMatches?.trend || "-0%"} trendUp={false} icon={XCircle} color={{ bg: "bg-[#F6A8B7]/20", text: "text-[#F6A8B7]", hex: "#EC4899" }} />
          <StatCard title="Match Success Rate" value={statsData?.successRate?.value || "0%"} trend={statsData?.successRate?.trend || "+0%"} trendUp={true} icon={Users} color={{ bg: "bg-blue-500/20", text: "text-blue-400", hex: "#3B82F6" }} />
        </div>

        {/* Filters */}
        <div className="bg-card border border-border shadow-md rounded-2xl p-4 rounded-2xl border border-white/5 flex flex-wrap items-center gap-4">
          <div className="relative flex-1 min-w-[200px]">
            <Search className="absolute z-10 left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[#707070]" />
            <Input 
              placeholder="Search by user name or email..." 
              className="pl-9 bg-card/5 border-white/10 rounded-xl"
              value={search}
              onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            />
          </div>
          
          <div className="flex items-center gap-2">
            <span className="text-xs text-[#707070]">Match Status</span>
            <Select value={statusFilter} onValueChange={(v) => { setStatusFilter(v); setPage(1); }}>
              <SelectTrigger className="w-[120px] bg-card/5 border-white/10 rounded-xl text-sm">
                <SelectValue placeholder="All" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="All">All</SelectItem>
                <SelectItem value="accepted">Accepted</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="rejected">Rejected</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <div className="flex items-center gap-2">
            <span className="text-xs text-[#707070]">Match Type</span>
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-[120px] bg-card/5 border-white/10 rounded-xl text-sm">
                <SelectValue placeholder="All" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="All">All</SelectItem>
                <SelectItem value="Compatibility Match">Compatibility Match</SelectItem>
                <SelectItem value="Premium Match">Premium Match</SelectItem>
              </SelectContent>
            </Select>
          </div>
          
          <div className="flex items-center gap-2">
            <span className="text-xs text-[#707070]">Compatibility Score</span>
            <Select value={compFilter} onValueChange={setCompFilter}>
              <SelectTrigger className="w-[120px] bg-card/5 border-white/10 rounded-xl text-sm">
                <SelectValue placeholder="All" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="All">All</SelectItem>
                <SelectItem value=">90%">&gt;90%</SelectItem>
                <SelectItem value=">80%">&gt;80%</SelectItem>
                <SelectItem value="<80%">&lt;80%</SelectItem>
              </SelectContent>
            </Select>
          </div>

          <Button variant="outline" className="border-white/10 bg-card/5 rounded-xl">
            Filters
          </Button>
          <Button variant="outline" className="border-white/10 bg-[#F6A8B7]/10 text-[#F6A8B7] hover:bg-[#F6A8B7]/20 hover:text-[#F5B75C] rounded-xl ml-auto">
            Bulk Actions
          </Button>
        </div>

        {/* Data Table */}
        <div className="bg-card border border-border shadow-md rounded-2xl rounded-2xl border border-white/5 overflow-hidden flex flex-col md:flex-row relative">
          
          <div className={`flex-1 transition-all duration-300 ${selectedMatch ? 'md:mr-[350px]' : ''}`}>
            <Table>
              <TableHeader className="bg-card/[0.02]">
                <TableRow className="border-white/10">
                  <TableHead className="w-[40px] pl-4"><input type="checkbox" className="rounded bg-transparent border-white/20" /></TableHead>
                  <TableHead>Match</TableHead>
                  <TableHead className="text-center">Compatibility</TableHead>
                  <TableHead>Match Score</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Match Type</TableHead>
                  <TableHead>Match Date</TableHead>
                  <TableHead className="text-right pr-4">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow><TableCell colSpan={8} className="text-center py-8">Loading...</TableCell></TableRow>
                ) : matchesData?.matches?.length === 0 ? (
                  <TableRow><TableCell colSpan={8} className="text-center py-8 text-[#707070]">No matches found.</TableCell></TableRow>
                ) : (
                  matchesData?.matches?.map((match: any) => (
                    <TableRow 
                      key={match.id} 
                      className={`border-b border-white/5 cursor-pointer hover:bg-card/[0.02] transition-colors ${selectedMatch?.id === match.id ? 'bg-card/[0.05]' : ''}`}
                      onClick={() => setSelectedMatch(match)}
                    >
                      <TableCell className="pl-4">
                        <input type="checkbox" className="rounded bg-transparent border-white/20" onClick={(e) => e.stopPropagation()} />
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-4">
                          <div className="flex items-center gap-2 min-w-[140px]">
                            <Avatar className="w-8 h-8">
                              <AvatarImage src={match.fromUser.avatar} />
                              <AvatarFallback>{match.fromUser.name[0]}</AvatarFallback>
                            </Avatar>
                            <div>
                              <div className="text-sm font-medium">{match.fromUser.name} <span className={match.fromUser.gender === 'female' ? "text-[#F6A8B7]" : "text-blue-400"}>{match.fromUser.gender === 'female' ? "♀" : "♂"}</span></div>
                              <div className="text-xs text-[#707070]">{match.fromUser.age}, {match.fromUser.location}</div>
                              <div className="text-[10px] text-[#707070] truncate w-24">{match.fromUser.email}</div>
                            </div>
                          </div>
                          <Heart className="w-3 h-3 text-[#F6A8B7] fill-[#F6A8B7] shrink-0" />
                          <div className="flex items-center gap-2 min-w-[140px]">
                            <Avatar className="w-8 h-8">
                              <AvatarImage src={match.toUser.avatar} />
                              <AvatarFallback>{match.toUser.name[0]}</AvatarFallback>
                            </Avatar>
                            <div>
                              <div className="text-sm font-medium">{match.toUser.name} <span className={match.toUser.gender === 'female' ? "text-[#F6A8B7]" : "text-blue-400"}>{match.toUser.gender === 'female' ? "♀" : "♂"}</span></div>
                              <div className="text-xs text-[#707070]">{match.toUser.age}, {match.toUser.location}</div>
                              <div className="text-[10px] text-[#707070] truncate w-24">{match.toUser.email}</div>
                            </div>
                          </div>
                        </div>
                      </TableCell>
                      <TableCell className="text-center">
                        <div className="inline-flex items-center justify-center w-10 h-10 rounded-full border-2 border-green-500 text-xs font-bold text-green-400">
                          {match.compatibility}%
                        </div>
                      </TableCell>
                      <TableCell>
                        <span className={`text-xs font-medium ${match.status === 'accepted' ? 'text-green-400' : match.status === 'pending' ? 'text-[#F6A8B7]' : 'text-red-400'}`}>
                          {match.status === 'accepted' ? 'Accepted' : match.status === 'pending' ? 'Pending' : 'Rejected'}
                        </span>
                      </TableCell>
                      <TableCell>
                        <Badge variant="outline" className={`bg-card/5 border-white/10 ${match.status === 'accepted' ? 'text-green-400' : match.status === 'pending' ? 'text-[#F6A8B7]' : 'text-red-400'}`}>
                          {match.status === 'accepted' ? 'Accepted' : match.status === 'pending' ? 'Pending' : 'Rejected'}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-1.5 text-xs">
                          {match.matchType === 'Premium Match' ? <Crown className="w-3.5 h-3.5 text-yellow-500" /> : <Heart className="w-3.5 h-3.5 text-[#F6A8B7]" />}
                          <span className={match.matchType === 'Premium Match' ? 'text-yellow-400' : 'text-[#F6A8B7]'}>{match.matchType}</span>
                        </div>
                      </TableCell>
                      <TableCell className="text-xs text-[#707070]">
                        <div>{format(new Date(match.matchDate), 'MMM d, yyyy')}</div>
                        <div>{format(new Date(match.matchDate), 'hh:mm a')}</div>
                      </TableCell>
                      <TableCell className="text-right pr-4">
                        <div className="flex justify-end items-center gap-2">
                          <Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-card/10" onClick={(e) => { e.stopPropagation(); setSelectedMatch(match); }}>
                            <Eye className="w-4 h-4 text-[#707070]" />
                          </Button>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild onClick={(e) => e.stopPropagation()}>
                              <Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-card/10">
                                <MoreVertical className="w-4 h-4 text-[#707070]" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end" className="bg-card border border-border shadow-md rounded-2xl border-white/10">
                              <DropdownMenuItem>View Details</DropdownMenuItem>
                              <DropdownMenuItem>Change Status</DropdownMenuItem>
                              <DropdownMenuItem className="text-red-400">Delete Match</DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
            
            {/* Pagination */}
            <div className="p-4 border-t border-white/10 flex items-center justify-between">
              <span className="text-xs text-[#707070]">
                Showing {(page - 1) * 10 + 1} to {Math.min(page * 10, matchesData?.total || 0)} of {matchesData?.total || 0} matches
              </span>
              <div className="flex items-center gap-1">
                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full" disabled={page === 1} onClick={() => setPage(p => p - 1)}>
                  <ChevronLeft className="w-4 h-4" />
                </Button>
                {[...Array(matchesData?.totalPages || 0)].map((_, i) => (
                  <Button 
                    key={i} 
                    variant={page === i + 1 ? "default" : "ghost"} 
                    className={`w-8 h-8 rounded-full ${page === i + 1 ? 'bg-[#F6A8B7] hover:bg-[#F6A8B7] text-white' : ''}`}
                    onClick={() => setPage(i + 1)}
                  >
                    {i + 1}
                  </Button>
                )).slice(Math.max(0, page - 3), Math.min(matchesData?.totalPages || 0, page + 2))}
                {matchesData?.totalPages > 5 && page < matchesData?.totalPages - 2 && <span className="px-2 text-[#707070]">...</span>}
                {matchesData?.totalPages > 5 && page < matchesData?.totalPages - 2 && (
                  <Button variant="ghost" className="w-8 h-8 rounded-full" onClick={() => setPage(matchesData.totalPages)}>{matchesData.totalPages}</Button>
                )}
                <Button variant="ghost" size="icon" className="w-8 h-8 rounded-full" disabled={page === matchesData?.totalPages} onClick={() => setPage(p => p + 1)}>
                  <ChevronRight className="w-4 h-4" />
                </Button>
              </div>
              <div className="flex items-center gap-2 text-xs text-[#707070]">
                Rows per page <Select defaultValue="10"><SelectTrigger className="w-[60px] h-8 bg-transparent border-white/10"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="10">10</SelectItem></SelectContent></Select>
              </div>
            </div>
          </div>

          {/* Right Side Panel */}
          <AnimatePresence>
            {selectedMatch && (
              <motion.div 
                initial={{ opacity: 0, x: 50 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 50 }}
                className="absolute top-0 right-0 bottom-0 w-full md:w-[350px] bg-[#1A1A24] border-l border-white/10 p-6 overflow-y-auto z-10 shadow-2xl"
              >
                <div className="flex items-center justify-between mb-6">
                  <h3 className="font-bold text-lg">Match Details</h3>
                  <Button variant="ghost" size="icon" className="h-8 w-8 rounded-full hover:bg-card/10" onClick={() => setSelectedMatch(null)}>
                    <XCircle className="w-5 h-5 text-[#707070]" />
                  </Button>
                </div>

                <div className="flex flex-col items-center mb-8 relative">
                  <div className="flex items-center justify-center relative w-full mb-4">
                    <div className="w-20 h-20 rounded-full border-2 border-green-500 absolute left-1/2 -translate-x-[90%] z-10 overflow-hidden bg-transparent">
                       <img src={selectedMatch.fromUser.avatar} className="w-full h-full object-cover" />
                    </div>
                    <div className="w-10 h-10 rounded-full bg-[#F6A8B7] flex items-center justify-center absolute left-1/2 -translate-x-1/2 z-20 border-[3px] border-[#1A1A24]">
                      <Heart className="w-4 h-4 text-white fill-white" />
                    </div>
                    <div className="w-20 h-20 rounded-full border-2 border-white/10 absolute left-1/2 -translate-x-[10%] z-0 overflow-hidden bg-transparent">
                       <img src={selectedMatch.toUser.avatar} className="w-full h-full object-cover" />
                    </div>
                  </div>
                  <div className="mt-20 w-full text-center">
                    <div className="flex justify-between px-4">
                      <div className="text-center w-1/2">
                        <p className="font-bold text-sm truncate">{selectedMatch.fromUser.name} <span className={selectedMatch.fromUser.gender === 'female' ? "text-[#F6A8B7]" : "text-blue-400"}>{selectedMatch.fromUser.gender === 'female' ? "♀" : "♂"}</span></p>
                        <p className="text-xs text-[#707070]">{selectedMatch.fromUser.age}, {selectedMatch.fromUser.location}</p>
                        <p className="text-[10px] text-[#707070] truncate">{selectedMatch.fromUser.email}</p>
                      </div>
                      <div className="text-center w-1/2">
                        <p className="font-bold text-sm truncate">{selectedMatch.toUser.name} <span className={selectedMatch.toUser.gender === 'female' ? "text-[#F6A8B7]" : "text-blue-400"}>{selectedMatch.toUser.gender === 'female' ? "♀" : "♂"}</span></p>
                        <p className="text-xs text-[#707070]">{selectedMatch.toUser.age}, {selectedMatch.toUser.location}</p>
                        <p className="text-[10px] text-[#707070] truncate">{selectedMatch.toUser.email}</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="mb-6 bg-card/[0.02] p-4 rounded-xl border border-white/5">
                  <div className="flex items-center justify-between mb-4">
                    <h4 className="text-sm font-semibold">Compatibility Breakdown</h4>
                  </div>
                  <div className="space-y-3">
                    {[
                      { label: "Personality Traits", val: 94, color: "bg-[#F6A8B7]" },
                      { label: "Values & Beliefs", val: 91, color: "bg-[#F6A8B7]" },
                      { label: "Lifestyle", val: 89, color: "bg-[#F6A8B7]" },
                      { label: "Communication", val: 88, color: "bg-blue-500" },
                      { label: "Relationship Goals", val: 90, color: "bg-green-500" },
                      { label: "Family Values", val: 85, color: "bg-[#F6A8B7]" }
                    ].map((item, i) => (
                      <div key={i}>
                        <div className="flex justify-between text-xs mb-1">
                          <span className="text-[#707070]">{item.label}</span>
                          <span className="font-medium">{item.val}%</span>
                        </div>
                        <div className="w-full h-1.5 rounded-full bg-card/10 overflow-hidden">
                          <motion.div initial={{ width: 0 }} animate={{ width: `${item.val}%` }} className={`h-full ${item.color}`} />
                        </div>
                      </div>
                    ))}
                  </div>
                  <Button variant="link" className="w-full text-xs text-[#F6A8B7] mt-2 p-0 h-auto">
                    View Full Analysis
                  </Button>
                </div>

                <div className="mb-6">
                  <h4 className="text-sm font-semibold mb-3">Match Information</h4>
                  <div className="space-y-2 text-xs">
                    <div className="flex justify-between"><span className="text-[#707070]">Match Type</span><span className="font-medium">{selectedMatch.matchType}</span></div>
                    <div className="flex justify-between"><span className="text-[#707070]">Initiated By</span><span className="font-medium">Compatibility Engine</span></div>
                    <div className="flex justify-between"><span className="text-[#707070]">Status</span><span className={`font-medium ${selectedMatch.status === 'accepted' ? 'text-green-400' : 'text-[#F6A8B7]'}`}>{selectedMatch.status === 'accepted' ? 'Accepted' : 'Pending'}</span></div>
                    <div className="flex justify-between"><span className="text-[#707070]">Match Date</span><span className="font-medium">{format(new Date(selectedMatch.matchDate), 'MMM d, yyyy hh:mm a')}</span></div>
                    <div className="flex justify-between"><span className="text-[#707070]">Last Interaction</span><span className="font-medium">{format(new Date(selectedMatch.updatedAt), 'MMM d, yyyy hh:mm a')}</span></div>
                  </div>
                </div>

                <div>
                  <h4 className="text-sm font-semibold mb-3">Quick Actions</h4>
                  <div className="grid grid-cols-2 gap-2">
                    <Button variant="outline" size="sm" className="bg-card/5 border-white/10 text-xs h-9"><Eye className="w-3.5 h-3.5 mr-2" /> View Both Profiles</Button>
                    <Button variant="outline" size="sm" className="bg-[#F6A8B7]/10 text-[#F6A8B7] border-[#F6A8B7]/20 hover:bg-[#F6A8B7]/20 text-xs h-9"><MessageCircle className="w-3.5 h-3.5 mr-2" /> Send Message</Button>
                    <Button variant="outline" size="sm" className="bg-card/5 border-white/10 text-xs h-9">Change Status</Button>
                    <Button variant="outline" size="sm" className="bg-red-500/10 text-red-400 border-red-500/20 hover:bg-red-500/20 text-xs h-9">Report Match</Button>
                  </div>
                </div>

              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
