
export const motivationQuotes = [
  "The right match will feel like peace, not drama.",
  "The right match will feel like a safe harbor in a storm.",
  "The right match will feel like endless support.",
  "The right match will feel like growth and understanding.",
  "The right match will feel like a foundation of trust.",
  "The right match will feel like mutual respect and care.",
  "The right match will feel like a journey of discovery.",
  "The right match will feel like unconditional love.",
  "The right match will feel like the patience to understand.",
  "The right match will feel like the courage to be vulnerable.",
  "The right match brings peace, not drama.",
  "The right match brings a safe harbor in a storm.",
  "The right match brings endless support.",
  "The right match brings growth and understanding.",
  "The right match brings a foundation of trust.",
  "The right match brings mutual respect and care.",
  "The right match brings a journey of discovery.",
  "The right match brings unconditional love.",
  "The right match brings the patience to understand.",
  "The right match brings the courage to be vulnerable.",
  "The right match creates peace, not drama.",
  "The right match creates a safe harbor in a storm.",
  "The right match creates endless support.",
  "The right match creates growth and understanding.",
  "The right match creates a foundation of trust.",
  "The right match creates mutual respect and care.",
  "The right match creates a journey of discovery.",
  "The right match creates unconditional love.",
  "The right match creates the patience to understand.",
  "The right match creates the courage to be vulnerable.",
  "The right match requires peace, not drama.",
  "The right match requires a safe harbor in a storm.",
  "The right match requires endless support.",
  "The right match requires growth and understanding.",
  "The right match requires a foundation of trust.",
  "The right match requires mutual respect and care.",
  "The right match requires a journey of discovery.",
  "The right match requires unconditional love.",
  "The right match requires the patience to understand.",
  "The right match requires the courage to be vulnerable.",
  "The right match is built on peace, not drama.",
  "The right match is built on a safe harbor in a storm.",
  "The right match is built on endless support.",
  "The right match is built on growth and understanding.",
  "The right match is built on a foundation of trust.",
  "The right match is built on mutual respect and care.",
  "The right match is built on a journey of discovery.",
  "The right match is built on unconditional love.",
  "The right match is built on the patience to understand.",
  "The right match is built on the courage to be vulnerable.",
  "The right match starts with peace, not drama.",
  "The right match starts with a safe harbor in a storm.",
  "The right match starts with endless support.",
  "The right match starts with growth and understanding.",
  "The right match starts with a foundation of trust.",
  "The right match starts with mutual respect and care.",
  "The right match starts with a journey of discovery.",
  "The right match starts with unconditional love.",
  "The right match starts with the patience to understand.",
  "The right match starts with the courage to be vulnerable.",
  "The right match leads to peace, not drama.",
  "The right match leads to a safe harbor in a storm.",
  "The right match leads to endless support.",
  "The right match leads to growth and understanding.",
  "The right match leads to a foundation of trust.",
  "The right match leads to mutual respect and care.",
  "The right match leads to a journey of discovery.",
  "The right match leads to unconditional love.",
  "The right match leads to the patience to understand.",
  "The right match leads to the courage to be vulnerable.",
  "The right match encourages peace, not drama.",
  "The right match encourages a safe harbor in a storm.",
  "The right match encourages endless support.",
  "The right match encourages growth and understanding.",
  "The right match encourages a foundation of trust.",
  "The right match encourages mutual respect and care.",
  "The right match encourages a journey of discovery.",
  "The right match encourages unconditional love.",
  "The right match encourages the patience to understand.",
  "The right match encourages the courage to be vulnerable.",
  "The right match inspires peace, not drama.",
  "The right match inspires a safe harbor in a storm.",
  "The right match inspires endless support.",
  "The right match inspires growth and understanding.",
  "The right match inspires a foundation of trust.",
  "The right match inspires mutual respect and care.",
  "The right match inspires a journey of discovery.",
  "The right match inspires unconditional love.",
  "The right match inspires the patience to understand.",
  "The right match inspires the courage to be vulnerable.",
  "The right match demands peace, not drama.",
  "The right match demands a safe harbor in a storm.",
  "The right match demands endless support.",
  "The right match demands growth and understanding.",
  "The right match demands a foundation of trust.",
  "The right match demands mutual respect and care.",
  "The right match demands a journey of discovery.",
  "The right match demands unconditional love.",
  "The right match demands the patience to understand.",
  "The right match demands the courage to be vulnerable.",
  "True love will feel like peace, not drama.",
  "True love will feel like a safe harbor in a storm.",
  "True love will feel like endless support.",
  "True love will feel like growth and understanding.",
  "True love will feel like a foundation of trust."
];
export const motivationImages = [
  "https://picsum.photos/id/100/800/600",
  "https://picsum.photos/id/101/800/600",
  "https://picsum.photos/id/102/800/600",
  "https://picsum.photos/id/103/800/600",
  "https://picsum.photos/id/104/800/600",
  "https://picsum.photos/id/105/800/600",
  "https://picsum.photos/id/106/800/600",
  "https://picsum.photos/id/107/800/600",
  "https://picsum.photos/id/108/800/600",
  "https://picsum.photos/id/109/800/600",
  "https://picsum.photos/id/110/800/600",
  "https://picsum.photos/id/111/800/600",
  "https://picsum.photos/id/112/800/600",
  "https://picsum.photos/id/113/800/600",
  "https://picsum.photos/id/114/800/600",
  "https://picsum.photos/id/115/800/600",
  "https://picsum.photos/id/116/800/600",
  "https://picsum.photos/id/117/800/600",
  "https://picsum.photos/id/118/800/600",
  "https://picsum.photos/id/119/800/600",
  "https://picsum.photos/id/120/800/600",
  "https://picsum.photos/id/121/800/600",
  "https://picsum.photos/id/122/800/600",
  "https://picsum.photos/id/123/800/600",
  "https://picsum.photos/id/124/800/600",
  "https://picsum.photos/id/125/800/600",
  "https://picsum.photos/id/126/800/600",
  "https://picsum.photos/id/127/800/600",
  "https://picsum.photos/id/128/800/600",
  "https://picsum.photos/id/129/800/600",
  "https://picsum.photos/id/130/800/600",
  "https://picsum.photos/id/131/800/600",
  "https://picsum.photos/id/132/800/600",
  "https://picsum.photos/id/133/800/600",
  "https://picsum.photos/id/134/800/600"
];
